Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -45,3 +45,17 @@ jobs:
             echo $CIRCLE_BRANCH
             git fetch origin "+refs/heads/*:refs/remotes/origin/*"
             semgrep ci --baseline-commit=$(git merge-base main HEAD) --json --output report-ssc.json
+            json_file=report-ssc.json
+            echo "Iterating through findings"
+            findings=$(jq -r '.results[]' "$json_file")
+            for k in $(jq '.results | keys | .[]' "$json_file"); do
+                value=$(jq -r ".results[$k]" "$json_file");
+                echo "$value" > finding_content.json
+                severity=$(jq -r '.extra.severity' "finding_content.json");
+                reachable=$(jq -r '.extra.sca_info.reachable' "finding_content.json");
+                if [[ $severity == "ERROR" && $reachable == "true" ]]; then
+                    echo "Exiting with error code 1"
+                    exit 1;
+                fi
+            done
+            echo "There are no reachable critical-high findings"
